
[[main]]
  name = "Features"
  url = "#features"
  weight = 1

[[main]]
  name = "Showcase"
  url = "#expo"
  weight = 3
  
[[main]]
  name = "Docs"
  url = "docs/"
  weight = 2

[[main]]
  name = "Demo"
  url = "https://phenocopter.csiro.au"
  weight = 10

[[main_right]]
  weight   = 1
  name     = "<i class=\"fab fa-github\"></i>"
  url      = "https://github.com/phenocopter/phenocopter-website"


# Documentation


[[docs]]
  name = "Getting started"
  identifier = "getting-started"
  weight = 1
  url = "/docs/getting-started/"

  
[[docs]]
  name = "Management"
  identifier = "managing-flights"
  weight = 2
  url = "/docs/managing-flights/"


[[docs]]
  name = "Processing"
  identifier = "processing-flight"
  weight = 3
  url = "/docs/processing-flight/"

[[docs]]
  name = "Advanced"
  identifier = "advanced-topic"
  weight = 4
  url = ""
  

[[docs]]
  name = "Functions"
  identifier = "phenotypic-function"
  weight = 5
  url = ""
 

[[docs]]
  name = "REST API"
  identifier = "restapi"
  weight = 6
  url = ""
  
 
[[docs]]
  name = "Deployment"
  identifier = "deployment"
  weight = 7
  url = "/docs/deployment/"
