
[[main]]
  name = "Features"
  url = "#features"
  weight = 1

[[main]]
  name = "Docs"
  url = "docs/"
  weight = 2

[[main]]
  name = "Demo"
  url = "https://phenocopter.csiro.au"
  weight = 10

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60


# Documentation


[[docs]]
  name = "Introduction"
  identifier = "introduction"
  weight = 1
  url = "/docs/"

[[docs]]
  name = "Getting started"
  identifier = "started"
  weight = 10
  url = ""


[[docs]]
  name = "Deployment"
  identifier = "deployment"
  weight = 20
  url = ""
