
[[main]]
  name = "Features"
  url = "#features"
  weight = 1

[[main]]
  name = "Docs"
  url = "docs/"
  weight = 2

[[main]]
  name = "Demo"
  url = "https://phenocopter.csiro.au"
  weight = 10

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60


# Documentation


[[docs]]
  name = "Getting started"
  identifier = "getting-started"
  weight = 1
  url = "/docs/getting-start/"

  
[[docs]]
  name = "Managing flights"
  identifier = "managing-flights"
  weight = 2
  url = "/docs/managing-flights/"


[[docs]]
  name = "Processing flight"
  identifier = "processing-flight"
  weight = 3
  url = "/docs/processing-flight/"
  
[[docs]]
  name = "Deployment"
  identifier = "deployment"
  weight = 4
  url = ""
