baseurl = "https://phenocopter.netlify.com/"
#baseurl = "https://localhost:44308/help"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "PhenoCopter Documentation"
theme = "hugo-theme-docdock"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
uglyurls = true
publishDir = "public"
[params]

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "Home"
identifier = "home"
url = "https://phenocopter.csiro.au"
weight = 3


[[menu.shortcuts]]
name = "Github Repo"
identifier = "hugodoc"
url = "https://github.com/phenocopter/PhenoCopterDoc"
weight = 2
